name: Deploy Staging to VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      # - name: Run Django tests
      #   run: |
      #     source env/bin/activate
      #     python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker using ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: fiardiel
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/fiardiel/budidayaplus_be:stable .
          docker push ghcr.io/fiardiel/budidayaplus_be:stable

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u fiardiel --password-stdin
            docker pull ghcr.io/fiardiel/budidayaplus_be:stable
            docker stop budidayaplus_be_prod || true
            docker rm budidayaplus_be_prod || true
            docker run -d --name budidayaplus_be_prod -p 8000:8000 --restart always \
              ghcr.io/fiardiel/budidayaplus_be:stable

            docker exec budidayaplus_be_prod python manage.py migrate
            docker exec budidayaplus_be_prod python manage.py loaddata data.json
